version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    depends_on:
      - postgres
      - redis
    networks:
      - taskcafe-net
    environment:
      TASKCAFE_DATABASE_HOST: postgres
      TASKCAFE_MIGRATE: "true"
      TASKCAFE_REDIS_HOST: redis
      TASKCAFE_REDIS_PORT: 6379
    volumes:
      - taskcafe-uploads:/root/uploads
    restart: always

  postgres:
    image: postgres:12.3-alpine
    restart: always
    networks:
      - taskcafe-net
    environment:
      POSTGRES_USER: taskcafe
      POSTGRES_PASSWORD: taskcafe_test
      POSTGRES_DB: taskcafe
    volumes:
      - taskcafe-postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    networks:
      - taskcafe-net

volumes:
  taskcafe-postgres:
  taskcafe-uploads:

networks:
  taskcafe
