name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull latest code
        run: |
          cd ~/SoftwareTaskTracker
          git pull origin main

      - name: Rebuild Docker
        run: |
          sudo docker-compose down
          sudo docker-compose up -d --build
