name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull latest code
        run: |
          cd ~/SoftwareTaskTracker
          git pull origin master

      - name: Rebuild Docker
        run: |
          cd ~/SoftwareTaskTracker
          sudo docker-compose -f docker-compose.yml down
          sudo docker-compose -f docker-compose.yml up -d --build
